/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const KnowledgeStatus = IDL.Variant({
  'verified' : IDL.Null,
  'contested' : IDL.Null,
  'revoked' : IDL.Null,
  'submitted' : IDL.Null,
  'superseded' : IDL.Null,
});
export const ProvenanceRef = IDL.Record({
  'hash' : IDL.Text,
  'kind' : IDL.Text,
  'reference' : IDL.Text,
});
export const NetworkKnowledgeRecord = IDL.Record({
  'provenance' : IDL.Vec(ProvenanceRef),
  'signature' : IDL.Vec(IDL.Nat8),
  'provenanceHash' : IDL.Text,
  'metadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'supersedes' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'logicalKey' : IDL.Text,
  'version' : IDL.Nat,
  'payloadHash' : IDL.Text,
  'recordId' : IDL.Text,
  'payloadLocator' : IDL.Text,
  'mediaType' : IDL.Text,
  'contributorNodeId' : IDL.Text,
  'schemaVersion' : IDL.Nat16,
  'namespace' : IDL.Text,
  'contributor' : IDL.Principal,
});
export const NetworkKnowledgeView = IDL.Record({
  'status' : KnowledgeStatus,
  'latestEventId' : IDL.Nat,
  'record' : NetworkKnowledgeRecord,
});
export const NetworkKnowledgeError = IDL.Variant({
  'duplicateRecord' : IDL.Null,
  'capacityExceeded' : IDL.Null,
  'selfVerificationNotAllowed' : IDL.Null,
  'invalidInput' : IDL.Text,
  'invalidSchemaVersion' : IDL.Null,
  'notContributor' : IDL.Null,
  'notFound' : IDL.Null,
  'nodeRevoked' : IDL.Null,
  'invalidSupersedes' : IDL.Null,
  'notNodeOwner' : IDL.Null,
  'invalidTransition' : IDL.Null,
  'anonymousNotAllowed' : IDL.Null,
  'nodeNotFound' : IDL.Null,
  'versionConflict' : IDL.Record({
    'expected' : IDL.Nat,
    'received' : IDL.Nat,
  }),
});
export const ViewResult = IDL.Variant({
  'ok' : NetworkKnowledgeView,
  'err' : NetworkKnowledgeError,
});
export const Hash = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Metrics = IDL.Record({
  'dataBytes' : IDL.Nat,
  'cpuMicros' : IDL.Nat,
  'gpuMicros' : IDL.Nat,
  'ramByteMicros' : IDL.Nat,
});
export const Evidence = IDL.Record({
  'method' : IDL.Text,
  'metrics' : Metrics,
  'workId' : IDL.Text,
  'evidenceHash' : IDL.Text,
});
export const SearchQuery = IDL.Record({
  'tags' : IDL.Vec(IDL.Text),
  'limit' : IDL.Opt(IDL.Nat),
  'exact' : IDL.Opt(IDL.Text),
  'keyword' : IDL.Opt(IDL.Text),
  'namespace' : IDL.Opt(IDL.Text),
});
export const KnowledgeId = IDL.Nat;
export const KnowledgeRecord = IDL.Record({
  'id' : KnowledgeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'hash' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'version' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'namespace' : IDL.Text,
});
export const Work = IDL.Record({
  'id' : IDL.Text,
  'contentHash' : IDL.Text,
  'nodeId' : IDL.Text,
  'acceptanceHash' : IDL.Text,
  'maxReward' : IDL.Nat,
  'kind' : IDL.Text,
});
export const StatusActionInput = IDL.Record({
  'signature' : IDL.Vec(IDL.Nat8),
  'nodeId' : IDL.Text,
  'recordId' : IDL.Text,
  'evidenceHash' : IDL.Text,
});
export const Version = IDL.Record({
  'id' : IDL.Nat,
  'hash' : Hash,
  'createdAt' : IDL.Int,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ExportScope = IDL.Variant({
  'complete' : IDL.Null,
  'selected' : IDL.Record({ 'ids' : IDL.Vec(IDL.Text) }),
  'single' : IDL.Record({ 'id' : IDL.Text }),
  'namespace' : IDL.Record({ 'namespace' : IDL.Text }),
});
export const ExportFormat = IDL.Variant({
  'json' : IDL.Null,
  'jsonl' : IDL.Null,
  'prismek' : IDL.Null,
});
export const ExportOptions = IDL.Record({ 'includeMetadata' : IDL.Bool });
export const ExportResult = IDL.Record({
  'payload' : IDL.Vec(IDL.Nat8),
  'recordCount' : IDL.Nat,
});
export const ExportPayload = IDL.Record({
  'records' : IDL.Vec(KnowledgeRecord),
  'schemaVersion' : IDL.Nat,
});
export const AuditAction = IDL.Variant({
  'importData' : IDL.Null,
  'delete' : IDL.Null,
  'create' : IDL.Null,
  'update' : IDL.Null,
  'export' : IDL.Null,
});
export const AuditEvent = IDL.Record({
  'id' : IDL.Nat,
  'action' : AuditAction,
  'atNs' : IDL.Int,
  'detail' : IDL.Text,
  'recordId' : IDL.Opt(IDL.Text),
  'namespace' : IDL.Opt(IDL.Text),
});
export const KnowledgeMetadata = IDL.Record({
  'id' : KnowledgeId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'version' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'namespace' : IDL.Text,
});
export const Account = IDL.Record({
  'bootstrap' : IDL.Nat,
  'spent' : IDL.Nat,
  'earned' : IDL.Nat,
  'consumedBytes' : IDL.Nat,
  'contribution' : Metrics,
});
export const Policy = IDL.Record({
  'loadBps' : IDL.Nat,
  'atNs' : IDL.Int,
  'ratioBps' : IDL.Nat,
  'epoch' : IDL.Nat,
  'version' : IDL.Nat,
  'evidenceHash' : IDL.Text,
});
export const Snapshot = IDL.Record({
  'adjustment' : IDL.Opt(IDL.Int),
  'debt' : IDL.Opt(IDL.Nat),
  'journalLength' : IDL.Opt(IDL.Nat),
  'journalTip' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'status' : IDL.Text,
  'available' : IDL.Nat,
  'account' : Account,
  'policy' : Policy,
});
export const KnowledgeStatusEvent = IDL.Record({
  'at' : IDL.Int,
  'status' : KnowledgeStatus,
  'eventId' : IDL.Nat,
  'signature' : IDL.Vec(IDL.Nat8),
  'nodeId' : IDL.Text,
  'recordId' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
  'evidenceHash' : IDL.Text,
});
export const EventsResult = IDL.Variant({
  'ok' : IDL.Vec(KnowledgeStatusEvent),
  'err' : NetworkKnowledgeError,
});
export const NetworkKnowledgeStats = IDL.Record({
  'verified' : IDL.Nat,
  'contested' : IDL.Nat,
  'revoked' : IDL.Nat,
  'submitted' : IDL.Nat,
  'superseded' : IDL.Nat,
  'totalEvents' : IDL.Nat,
  'totalRecords' : IDL.Nat,
});
export const StatsResult = IDL.Variant({
  'ok' : NetworkKnowledgeStats,
  'err' : NetworkKnowledgeError,
});
export const NodeStatus = IDL.Variant({
  'active' : IDL.Null,
  'revoked' : IDL.Null,
  'degraded' : IDL.Null,
  'offline' : IDL.Null,
  'registered' : IDL.Null,
});
export const CpuCapability = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'architecture' : IDL.Text,
  'logicalCores' : IDL.Nat,
});
export const AcceleratorKind = IDL.Variant({
  'cpu' : IDL.Null,
  'gpu' : IDL.Null,
  'lpu' : IDL.Null,
  'npu' : IDL.Null,
  'other' : IDL.Null,
  'fpga' : IDL.Null,
});
export const AcceleratorCapability = IDL.Record({
  'model' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'kind' : AcceleratorKind,
  'architecture' : IDL.Text,
  'supportedPrecisions' : IDL.Vec(IDL.Text),
  'memoryBytes' : IDL.Nat,
  'vendor' : IDL.Text,
  'runtimeApis' : IDL.Vec(IDL.Text),
  'limits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ChromaCapability = IDL.Record({
  'cpu' : CpuCapability,
  'supportedModels' : IDL.Vec(IDL.Text),
  'signature' : IDL.Vec(IDL.Nat8),
  'expiresAt' : IDL.Int,
  'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'nodeId' : IDL.Text,
  'architectures' : IDL.Vec(IDL.Text),
  'capabilityDigest' : IDL.Text,
  'publishedAt' : IDL.Int,
  'memoryBytes' : IDL.Nat,
  'resourcePolicyDigest' : IDL.Text,
  'accelerators' : IDL.Vec(AcceleratorCapability),
  'supportedTransports' : IDL.Vec(IDL.Text),
  'operatingSystems' : IDL.Vec(IDL.Text),
  'schemaVersion' : IDL.Nat16,
  'supportedRuntimes' : IDL.Vec(IDL.Text),
  'sandboxFeatures' : IDL.Vec(IDL.Text),
  'sequence' : IDL.Nat,
});
export const NodeRecord = IDL.Record({
  'status' : NodeStatus,
  'protocolVersion' : IDL.Text,
  'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'nodeId' : IDL.Text,
  'owner' : IDL.Principal,
  'publicKey' : IDL.Vec(IDL.Nat8),
  'updatedAt' : IDL.Int,
  'capabilitySequence' : IDL.Nat,
  'lastHeartbeatAt' : IDL.Opt(IDL.Int),
  'heartbeatSequence' : IDL.Nat,
  'schemaVersion' : IDL.Nat16,
  'registeredAt' : IDL.Int,
  'capability' : IDL.Opt(ChromaCapability),
});
export const NodeRegistryStats = IDL.Record({
  'active' : IDL.Nat,
  'revoked' : IDL.Nat,
  'totalNodes' : IDL.Nat,
  'degraded' : IDL.Nat,
  'offline' : IDL.Nat,
  'registered' : IDL.Nat,
});
export const VersionInfo = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'version' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'namespace' : IDL.Text,
});
export const HeartbeatInput = IDL.Record({
  'protocolVersion' : IDL.Text,
  'nodeId' : IDL.Text,
  'sequence' : IDL.Nat,
});
export const RegistryError = IDL.Variant({
  'staleSequence' : IDL.Record({ 'current' : IDL.Nat, 'received' : IDL.Nat }),
  'revoked' : IDL.Null,
  'invalidProtocolVersion' : IDL.Null,
  'invalidInput' : IDL.Text,
  'invalidPublicKey' : IDL.Null,
  'invalidSchemaVersion' : IDL.Null,
  'capabilityExpired' : IDL.Null,
  'notFound' : IDL.Null,
  'notOwner' : IDL.Null,
  'anonymousNotAllowed' : IDL.Null,
  'nodeIdMismatch' : IDL.Null,
  'sequenceConflict' : IDL.Record({ 'sequence' : IDL.Nat }),
  'registryFull' : IDL.Null,
});
export const NodeResult = IDL.Variant({
  'ok' : NodeRecord,
  'err' : RegistryError,
});
export const ImportFormat = IDL.Variant({
  'csv' : IDL.Null,
  'json' : IDL.Null,
  'text' : IDL.Null,
  'prismek' : IDL.Null,
  'markdown' : IDL.Null,
});
export const ImportOptions = IDL.Record({
  'source' : IDL.Opt(IDL.Text),
  'overwrite' : IDL.Bool,
  'namespace' : IDL.Text,
});
export const ImportResult__1 = IDL.Record({
  'imported' : IDL.Nat,
  'skipped' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
});
export const KnowledgeInput = IDL.Record({
  'id' : KnowledgeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'namespace' : IDL.Text,
});
export const ImportPayload = IDL.Record({
  'records' : IDL.Vec(KnowledgeInput),
  'schemaVersion' : IDL.Nat,
});
export const ImportResult = IDL.Record({
  'imported' : IDL.Nat,
  'skipped' : IDL.Nat,
});
export const DedupEntry = IDL.Record({ 'hash' : Hash, 'refCount' : IDL.Nat });
export const ViewsResult = IDL.Variant({
  'ok' : IDL.Vec(NetworkKnowledgeView),
  'err' : NetworkKnowledgeError,
});
export const PublishCapabilitiesInput = IDL.Record({
  'cpu' : CpuCapability,
  'supportedModels' : IDL.Vec(IDL.Text),
  'signature' : IDL.Vec(IDL.Nat8),
  'expiresAt' : IDL.Int,
  'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'nodeId' : IDL.Text,
  'architectures' : IDL.Vec(IDL.Text),
  'capabilityDigest' : IDL.Text,
  'memoryBytes' : IDL.Nat,
  'resourcePolicyDigest' : IDL.Text,
  'accelerators' : IDL.Vec(AcceleratorCapability),
  'supportedTransports' : IDL.Vec(IDL.Text),
  'operatingSystems' : IDL.Vec(IDL.Text),
  'schemaVersion' : IDL.Nat16,
  'supportedRuntimes' : IDL.Vec(IDL.Text),
  'sandboxFeatures' : IDL.Vec(IDL.Text),
  'sequence' : IDL.Nat,
});
export const RegisterNodeInput = IDL.Record({
  'protocolVersion' : IDL.Text,
  'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'publicKey' : IDL.Vec(IDL.Nat8),
  'schemaVersion' : IDL.Nat16,
});
export const Load = IDL.Record({
  'observedAt' : IDL.Int,
  'demand' : IDL.Nat,
  'epoch' : IDL.Nat,
  'capacity' : IDL.Nat,
  'evidenceHash' : IDL.Text,
});
export const SearchResult = IDL.Record({
  'score' : IDL.Nat,
  'record' : KnowledgeRecord,
});
export const SearchResponse = IDL.Record({
  'total' : IDL.Nat,
  'results' : IDL.Vec(SearchResult),
});
export const Address = IDL.Text;
export const Availability = IDL.Variant({
  'available' : IDL.Null,
  'degraded' : IDL.Text,
  'unavailable' : IDL.Null,
});
export const Capacity = IDL.Record({
  'totalBytes' : IDL.Nat,
  'usedBytes' : IDL.Nat,
});
export const Integrity = IDL.Variant({ 'ok' : IDL.Null, 'corrupt' : IDL.Text });
export const StorageError = IDL.Variant({
  'capacityExceeded' : IDL.Null,
  'other' : IDL.Text,
  'integrityError' : IDL.Null,
  'notFound' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Nat8),
  'err' : StorageError,
});
export const Result = IDL.Variant({ 'ok' : Address, 'err' : StorageError });
export const SubmitNetworkKnowledgeInput = IDL.Record({
  'provenance' : IDL.Vec(ProvenanceRef),
  'signature' : IDL.Vec(IDL.Nat8),
  'provenanceHash' : IDL.Text,
  'nodeId' : IDL.Text,
  'metadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'supersedes' : IDL.Opt(IDL.Text),
  'logicalKey' : IDL.Text,
  'version' : IDL.Nat,
  'payloadHash' : IDL.Text,
  'payloadLocator' : IDL.Text,
  'mediaType' : IDL.Text,
  'schemaVersion' : IDL.Nat16,
  'namespace' : IDL.Text,
});
export const VerificationState = IDL.Variant({
  'verified' : IDL.Null,
  'missingPayload' : IDL.Null,
  'hashMismatch' : IDL.Null,
});
export const VerificationResult = IDL.Record({
  'hash' : Hash,
  'state' : VerificationState,
});
export const VerifyResult = IDL.Record({
  'id' : KnowledgeId,
  'version' : IDL.Nat,
  'exists' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acquireVerifiedKnowledgeV1' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [ViewResult],
      [],
    ),
  'addPayload' : IDL.Func([IDL.Vec(IDL.Nat8)], [Hash], []),
  'admitNetworkNodeV1' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attestNetworkWorkV1' : IDL.Func([Evidence], [IDL.Nat], []),
  'buildContext' : IDL.Func([SearchQuery], [IDL.Vec(KnowledgeRecord)], []),
  'commissionNetworkWorkV1' : IDL.Func([Work], [], []),
  'contestNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
  'createVersion' : IDL.Func([Hash], [Version], []),
  'deleteKnowledge' : IDL.Func([KnowledgeId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'exportData' : IDL.Func(
      [ExportScope, ExportFormat, ExportOptions],
      [ExportResult],
      [],
    ),
  'exportKnowledge' : IDL.Func([], [ExportPayload], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAuditEventsByAction' : IDL.Func(
      [AuditAction],
      [IDL.Vec(AuditEvent)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKnowledgeMetadata' : IDL.Func(
      [KnowledgeId],
      [IDL.Opt(KnowledgeMetadata)],
      [],
    ),
  'getNetworkBalanceV1' : IDL.Func([IDL.Text], [Snapshot], ['query']),
  'getNetworkKnowledge' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ViewResult],
      ['query'],
    ),
  'getNetworkKnowledgeEvents' : IDL.Func(
      [IDL.Text, IDL.Text],
      [EventsResult],
      ['query'],
    ),
  'getNetworkKnowledgeStats' : IDL.Func([IDL.Text], [StatsResult], ['query']),
  'getNode' : IDL.Func([IDL.Text], [IDL.Opt(NodeRecord)], ['query']),
  'getNodeRegistryStats' : IDL.Func([], [NodeRegistryStats], ['query']),
  'getRefCount' : IDL.Func([Hash], [IDL.Opt(IDL.Nat)], ['query']),
  'getStorageStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBytes' : IDL.Nat,
          'versionCount' : IDL.Nat,
          'recordCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getVersionHistory' : IDL.Func([KnowledgeId], [IDL.Vec(VersionInfo)], []),
  'heartbeat' : IDL.Func([HeartbeatInput], [NodeResult], []),
  'importData' : IDL.Func(
      [ImportFormat, IDL.Vec(IDL.Nat8), ImportOptions],
      [ImportResult__1],
      [],
    ),
  'importKnowledge' : IDL.Func([ImportPayload], [ImportResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAuditEvents' : IDL.Func([], [IDL.Vec(AuditEvent)], ['query']),
  'listDedupEntries' : IDL.Func([], [IDL.Vec(DedupEntry)], ['query']),
  'listKnowledge' : IDL.Func([], [IDL.Vec(KnowledgeRecord)], []),
  'listMyNodes' : IDL.Func([], [IDL.Vec(NodeRecord)], ['query']),
  'listNetworkKnowledgeByKey' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ViewsResult],
      ['query'],
    ),
  'listNodes' : IDL.Func([], [IDL.Vec(NodeRecord)], ['query']),
  'listVersions' : IDL.Func([], [IDL.Vec(Version)], ['query']),
  'publishCapabilities' : IDL.Func(
      [PublishCapabilitiesInput],
      [NodeResult],
      [],
    ),
  'registerNode' : IDL.Func([RegisterNodeInput], [NodeResult], []),
  'removePayload' : IDL.Func([Hash], [IDL.Bool], []),
  'reportNetworkLoadV1' : IDL.Func([Load], [Policy], []),
  'restoreVersion' : IDL.Func(
      [KnowledgeId, IDL.Nat],
      [IDL.Opt(KnowledgeRecord)],
      [],
    ),
  'restoreVersionById' : IDL.Func([IDL.Nat], [IDL.Opt(Hash)], ['query']),
  'retrieveKnowledge' : IDL.Func([KnowledgeId], [IDL.Opt(KnowledgeRecord)], []),
  'revokeNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
  'revokeNode' : IDL.Func([IDL.Text], [NodeResult], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchKnowledge' : IDL.Func([SearchQuery], [SearchResponse], []),
  'searchVerifiedKnowledgeV1' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'version' : IDL.Nat,
            'payloadHash' : IDL.Text,
            'recordId' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'setNetworkVerifierV1' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Bool],
      [],
      [],
    ),
  'storageAddressMapping' : IDL.Func([IDL.Text], [IDL.Opt(Address)], ['query']),
  'storageAvailability' : IDL.Func([], [Availability], []),
  'storageCapacity' : IDL.Func([], [Capacity], []),
  'storageIndex' : IDL.Func([], [IDL.Vec(Address)], []),
  'storageIntegrity' : IDL.Func([Address], [Integrity], []),
  'storageRead' : IDL.Func([Address], [Result_1], []),
  'storageWrite' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [Result], []),
  'storeKnowledge' : IDL.Func([KnowledgeInput], [KnowledgeId], []),
  'submitNetworkKnowledge' : IDL.Func(
      [SubmitNetworkKnowledgeInput],
      [ViewResult],
      [],
    ),
  'updateKnowledge' : IDL.Func(
      [KnowledgeInput],
      [IDL.Opt(KnowledgeRecord)],
      [],
    ),
  'verifyBatch' : IDL.Func(
      [IDL.Vec(Hash)],
      [IDL.Vec(VerificationResult)],
      ['query'],
    ),
  'verifyKnowledge' : IDL.Func([KnowledgeId], [VerifyResult], []),
  'verifyNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
  'verifyPayload' : IDL.Func(
      [Hash, IDL.Vec(IDL.Nat8)],
      [VerificationState],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const KnowledgeStatus = IDL.Variant({
    'verified' : IDL.Null,
    'contested' : IDL.Null,
    'revoked' : IDL.Null,
    'submitted' : IDL.Null,
    'superseded' : IDL.Null,
  });
  const ProvenanceRef = IDL.Record({
    'hash' : IDL.Text,
    'kind' : IDL.Text,
    'reference' : IDL.Text,
  });
  const NetworkKnowledgeRecord = IDL.Record({
    'provenance' : IDL.Vec(ProvenanceRef),
    'signature' : IDL.Vec(IDL.Nat8),
    'provenanceHash' : IDL.Text,
    'metadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'supersedes' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'logicalKey' : IDL.Text,
    'version' : IDL.Nat,
    'payloadHash' : IDL.Text,
    'recordId' : IDL.Text,
    'payloadLocator' : IDL.Text,
    'mediaType' : IDL.Text,
    'contributorNodeId' : IDL.Text,
    'schemaVersion' : IDL.Nat16,
    'namespace' : IDL.Text,
    'contributor' : IDL.Principal,
  });
  const NetworkKnowledgeView = IDL.Record({
    'status' : KnowledgeStatus,
    'latestEventId' : IDL.Nat,
    'record' : NetworkKnowledgeRecord,
  });
  const NetworkKnowledgeError = IDL.Variant({
    'duplicateRecord' : IDL.Null,
    'capacityExceeded' : IDL.Null,
    'selfVerificationNotAllowed' : IDL.Null,
    'invalidInput' : IDL.Text,
    'invalidSchemaVersion' : IDL.Null,
    'notContributor' : IDL.Null,
    'notFound' : IDL.Null,
    'nodeRevoked' : IDL.Null,
    'invalidSupersedes' : IDL.Null,
    'notNodeOwner' : IDL.Null,
    'invalidTransition' : IDL.Null,
    'anonymousNotAllowed' : IDL.Null,
    'nodeNotFound' : IDL.Null,
    'versionConflict' : IDL.Record({
      'expected' : IDL.Nat,
      'received' : IDL.Nat,
    }),
  });
  const ViewResult = IDL.Variant({
    'ok' : NetworkKnowledgeView,
    'err' : NetworkKnowledgeError,
  });
  const Hash = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Metrics = IDL.Record({
    'dataBytes' : IDL.Nat,
    'cpuMicros' : IDL.Nat,
    'gpuMicros' : IDL.Nat,
    'ramByteMicros' : IDL.Nat,
  });
  const Evidence = IDL.Record({
    'method' : IDL.Text,
    'metrics' : Metrics,
    'workId' : IDL.Text,
    'evidenceHash' : IDL.Text,
  });
  const SearchQuery = IDL.Record({
    'tags' : IDL.Vec(IDL.Text),
    'limit' : IDL.Opt(IDL.Nat),
    'exact' : IDL.Opt(IDL.Text),
    'keyword' : IDL.Opt(IDL.Text),
    'namespace' : IDL.Opt(IDL.Text),
  });
  const KnowledgeId = IDL.Nat;
  const KnowledgeRecord = IDL.Record({
    'id' : KnowledgeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'hash' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'namespace' : IDL.Text,
  });
  const Work = IDL.Record({
    'id' : IDL.Text,
    'contentHash' : IDL.Text,
    'nodeId' : IDL.Text,
    'acceptanceHash' : IDL.Text,
    'maxReward' : IDL.Nat,
    'kind' : IDL.Text,
  });
  const StatusActionInput = IDL.Record({
    'signature' : IDL.Vec(IDL.Nat8),
    'nodeId' : IDL.Text,
    'recordId' : IDL.Text,
    'evidenceHash' : IDL.Text,
  });
  const Version = IDL.Record({
    'id' : IDL.Nat,
    'hash' : Hash,
    'createdAt' : IDL.Int,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ExportScope = IDL.Variant({
    'complete' : IDL.Null,
    'selected' : IDL.Record({ 'ids' : IDL.Vec(IDL.Text) }),
    'single' : IDL.Record({ 'id' : IDL.Text }),
    'namespace' : IDL.Record({ 'namespace' : IDL.Text }),
  });
  const ExportFormat = IDL.Variant({
    'json' : IDL.Null,
    'jsonl' : IDL.Null,
    'prismek' : IDL.Null,
  });
  const ExportOptions = IDL.Record({ 'includeMetadata' : IDL.Bool });
  const ExportResult = IDL.Record({
    'payload' : IDL.Vec(IDL.Nat8),
    'recordCount' : IDL.Nat,
  });
  const ExportPayload = IDL.Record({
    'records' : IDL.Vec(KnowledgeRecord),
    'schemaVersion' : IDL.Nat,
  });
  const AuditAction = IDL.Variant({
    'importData' : IDL.Null,
    'delete' : IDL.Null,
    'create' : IDL.Null,
    'update' : IDL.Null,
    'export' : IDL.Null,
  });
  const AuditEvent = IDL.Record({
    'id' : IDL.Nat,
    'action' : AuditAction,
    'atNs' : IDL.Int,
    'detail' : IDL.Text,
    'recordId' : IDL.Opt(IDL.Text),
    'namespace' : IDL.Opt(IDL.Text),
  });
  const KnowledgeMetadata = IDL.Record({
    'id' : KnowledgeId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'namespace' : IDL.Text,
  });
  const Account = IDL.Record({
    'bootstrap' : IDL.Nat,
    'spent' : IDL.Nat,
    'earned' : IDL.Nat,
    'consumedBytes' : IDL.Nat,
    'contribution' : Metrics,
  });
  const Policy = IDL.Record({
    'loadBps' : IDL.Nat,
    'atNs' : IDL.Int,
    'ratioBps' : IDL.Nat,
    'epoch' : IDL.Nat,
    'version' : IDL.Nat,
    'evidenceHash' : IDL.Text,
  });
  const Snapshot = IDL.Record({
    'adjustment' : IDL.Opt(IDL.Int),
    'debt' : IDL.Opt(IDL.Nat),
    'journalLength' : IDL.Opt(IDL.Nat),
    'journalTip' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'status' : IDL.Text,
    'available' : IDL.Nat,
    'account' : Account,
    'policy' : Policy,
  });
  const KnowledgeStatusEvent = IDL.Record({
    'at' : IDL.Int,
    'status' : KnowledgeStatus,
    'eventId' : IDL.Nat,
    'signature' : IDL.Vec(IDL.Nat8),
    'nodeId' : IDL.Text,
    'recordId' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
    'evidenceHash' : IDL.Text,
  });
  const EventsResult = IDL.Variant({
    'ok' : IDL.Vec(KnowledgeStatusEvent),
    'err' : NetworkKnowledgeError,
  });
  const NetworkKnowledgeStats = IDL.Record({
    'verified' : IDL.Nat,
    'contested' : IDL.Nat,
    'revoked' : IDL.Nat,
    'submitted' : IDL.Nat,
    'superseded' : IDL.Nat,
    'totalEvents' : IDL.Nat,
    'totalRecords' : IDL.Nat,
  });
  const StatsResult = IDL.Variant({
    'ok' : NetworkKnowledgeStats,
    'err' : NetworkKnowledgeError,
  });
  const NodeStatus = IDL.Variant({
    'active' : IDL.Null,
    'revoked' : IDL.Null,
    'degraded' : IDL.Null,
    'offline' : IDL.Null,
    'registered' : IDL.Null,
  });
  const CpuCapability = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'architecture' : IDL.Text,
    'logicalCores' : IDL.Nat,
  });
  const AcceleratorKind = IDL.Variant({
    'cpu' : IDL.Null,
    'gpu' : IDL.Null,
    'lpu' : IDL.Null,
    'npu' : IDL.Null,
    'other' : IDL.Null,
    'fpga' : IDL.Null,
  });
  const AcceleratorCapability = IDL.Record({
    'model' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'kind' : AcceleratorKind,
    'architecture' : IDL.Text,
    'supportedPrecisions' : IDL.Vec(IDL.Text),
    'memoryBytes' : IDL.Nat,
    'vendor' : IDL.Text,
    'runtimeApis' : IDL.Vec(IDL.Text),
    'limits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ChromaCapability = IDL.Record({
    'cpu' : CpuCapability,
    'supportedModels' : IDL.Vec(IDL.Text),
    'signature' : IDL.Vec(IDL.Nat8),
    'expiresAt' : IDL.Int,
    'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'nodeId' : IDL.Text,
    'architectures' : IDL.Vec(IDL.Text),
    'capabilityDigest' : IDL.Text,
    'publishedAt' : IDL.Int,
    'memoryBytes' : IDL.Nat,
    'resourcePolicyDigest' : IDL.Text,
    'accelerators' : IDL.Vec(AcceleratorCapability),
    'supportedTransports' : IDL.Vec(IDL.Text),
    'operatingSystems' : IDL.Vec(IDL.Text),
    'schemaVersion' : IDL.Nat16,
    'supportedRuntimes' : IDL.Vec(IDL.Text),
    'sandboxFeatures' : IDL.Vec(IDL.Text),
    'sequence' : IDL.Nat,
  });
  const NodeRecord = IDL.Record({
    'status' : NodeStatus,
    'protocolVersion' : IDL.Text,
    'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'nodeId' : IDL.Text,
    'owner' : IDL.Principal,
    'publicKey' : IDL.Vec(IDL.Nat8),
    'updatedAt' : IDL.Int,
    'capabilitySequence' : IDL.Nat,
    'lastHeartbeatAt' : IDL.Opt(IDL.Int),
    'heartbeatSequence' : IDL.Nat,
    'schemaVersion' : IDL.Nat16,
    'registeredAt' : IDL.Int,
    'capability' : IDL.Opt(ChromaCapability),
  });
  const NodeRegistryStats = IDL.Record({
    'active' : IDL.Nat,
    'revoked' : IDL.Nat,
    'totalNodes' : IDL.Nat,
    'degraded' : IDL.Nat,
    'offline' : IDL.Nat,
    'registered' : IDL.Nat,
  });
  const VersionInfo = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'namespace' : IDL.Text,
  });
  const HeartbeatInput = IDL.Record({
    'protocolVersion' : IDL.Text,
    'nodeId' : IDL.Text,
    'sequence' : IDL.Nat,
  });
  const RegistryError = IDL.Variant({
    'staleSequence' : IDL.Record({ 'current' : IDL.Nat, 'received' : IDL.Nat }),
    'revoked' : IDL.Null,
    'invalidProtocolVersion' : IDL.Null,
    'invalidInput' : IDL.Text,
    'invalidPublicKey' : IDL.Null,
    'invalidSchemaVersion' : IDL.Null,
    'capabilityExpired' : IDL.Null,
    'notFound' : IDL.Null,
    'notOwner' : IDL.Null,
    'anonymousNotAllowed' : IDL.Null,
    'nodeIdMismatch' : IDL.Null,
    'sequenceConflict' : IDL.Record({ 'sequence' : IDL.Nat }),
    'registryFull' : IDL.Null,
  });
  const NodeResult = IDL.Variant({ 'ok' : NodeRecord, 'err' : RegistryError });
  const ImportFormat = IDL.Variant({
    'csv' : IDL.Null,
    'json' : IDL.Null,
    'text' : IDL.Null,
    'prismek' : IDL.Null,
    'markdown' : IDL.Null,
  });
  const ImportOptions = IDL.Record({
    'source' : IDL.Opt(IDL.Text),
    'overwrite' : IDL.Bool,
    'namespace' : IDL.Text,
  });
  const ImportResult__1 = IDL.Record({
    'imported' : IDL.Nat,
    'skipped' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
  });
  const KnowledgeInput = IDL.Record({
    'id' : KnowledgeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'namespace' : IDL.Text,
  });
  const ImportPayload = IDL.Record({
    'records' : IDL.Vec(KnowledgeInput),
    'schemaVersion' : IDL.Nat,
  });
  const ImportResult = IDL.Record({
    'imported' : IDL.Nat,
    'skipped' : IDL.Nat,
  });
  const DedupEntry = IDL.Record({ 'hash' : Hash, 'refCount' : IDL.Nat });
  const ViewsResult = IDL.Variant({
    'ok' : IDL.Vec(NetworkKnowledgeView),
    'err' : NetworkKnowledgeError,
  });
  const PublishCapabilitiesInput = IDL.Record({
    'cpu' : CpuCapability,
    'supportedModels' : IDL.Vec(IDL.Text),
    'signature' : IDL.Vec(IDL.Nat8),
    'expiresAt' : IDL.Int,
    'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'nodeId' : IDL.Text,
    'architectures' : IDL.Vec(IDL.Text),
    'capabilityDigest' : IDL.Text,
    'memoryBytes' : IDL.Nat,
    'resourcePolicyDigest' : IDL.Text,
    'accelerators' : IDL.Vec(AcceleratorCapability),
    'supportedTransports' : IDL.Vec(IDL.Text),
    'operatingSystems' : IDL.Vec(IDL.Text),
    'schemaVersion' : IDL.Nat16,
    'supportedRuntimes' : IDL.Vec(IDL.Text),
    'sandboxFeatures' : IDL.Vec(IDL.Text),
    'sequence' : IDL.Nat,
  });
  const RegisterNodeInput = IDL.Record({
    'protocolVersion' : IDL.Text,
    'publicMetadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'publicKey' : IDL.Vec(IDL.Nat8),
    'schemaVersion' : IDL.Nat16,
  });
  const Load = IDL.Record({
    'observedAt' : IDL.Int,
    'demand' : IDL.Nat,
    'epoch' : IDL.Nat,
    'capacity' : IDL.Nat,
    'evidenceHash' : IDL.Text,
  });
  const SearchResult = IDL.Record({
    'score' : IDL.Nat,
    'record' : KnowledgeRecord,
  });
  const SearchResponse = IDL.Record({
    'total' : IDL.Nat,
    'results' : IDL.Vec(SearchResult),
  });
  const Address = IDL.Text;
  const Availability = IDL.Variant({
    'available' : IDL.Null,
    'degraded' : IDL.Text,
    'unavailable' : IDL.Null,
  });
  const Capacity = IDL.Record({
    'totalBytes' : IDL.Nat,
    'usedBytes' : IDL.Nat,
  });
  const Integrity = IDL.Variant({ 'ok' : IDL.Null, 'corrupt' : IDL.Text });
  const StorageError = IDL.Variant({
    'capacityExceeded' : IDL.Null,
    'other' : IDL.Text,
    'integrityError' : IDL.Null,
    'notFound' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Vec(IDL.Nat8),
    'err' : StorageError,
  });
  const Result = IDL.Variant({ 'ok' : Address, 'err' : StorageError });
  const SubmitNetworkKnowledgeInput = IDL.Record({
    'provenance' : IDL.Vec(ProvenanceRef),
    'signature' : IDL.Vec(IDL.Nat8),
    'provenanceHash' : IDL.Text,
    'nodeId' : IDL.Text,
    'metadata' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'supersedes' : IDL.Opt(IDL.Text),
    'logicalKey' : IDL.Text,
    'version' : IDL.Nat,
    'payloadHash' : IDL.Text,
    'payloadLocator' : IDL.Text,
    'mediaType' : IDL.Text,
    'schemaVersion' : IDL.Nat16,
    'namespace' : IDL.Text,
  });
  const VerificationState = IDL.Variant({
    'verified' : IDL.Null,
    'missingPayload' : IDL.Null,
    'hashMismatch' : IDL.Null,
  });
  const VerificationResult = IDL.Record({
    'hash' : Hash,
    'state' : VerificationState,
  });
  const VerifyResult = IDL.Record({
    'id' : KnowledgeId,
    'version' : IDL.Nat,
    'exists' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acquireVerifiedKnowledgeV1' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [ViewResult],
        [],
      ),
    'addPayload' : IDL.Func([IDL.Vec(IDL.Nat8)], [Hash], []),
    'admitNetworkNodeV1' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attestNetworkWorkV1' : IDL.Func([Evidence], [IDL.Nat], []),
    'buildContext' : IDL.Func([SearchQuery], [IDL.Vec(KnowledgeRecord)], []),
    'commissionNetworkWorkV1' : IDL.Func([Work], [], []),
    'contestNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
    'createVersion' : IDL.Func([Hash], [Version], []),
    'deleteKnowledge' : IDL.Func([KnowledgeId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'exportData' : IDL.Func(
        [ExportScope, ExportFormat, ExportOptions],
        [ExportResult],
        [],
      ),
    'exportKnowledge' : IDL.Func([], [ExportPayload], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAuditEventsByAction' : IDL.Func(
        [AuditAction],
        [IDL.Vec(AuditEvent)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKnowledgeMetadata' : IDL.Func(
        [KnowledgeId],
        [IDL.Opt(KnowledgeMetadata)],
        [],
      ),
    'getNetworkBalanceV1' : IDL.Func([IDL.Text], [Snapshot], ['query']),
    'getNetworkKnowledge' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ViewResult],
        ['query'],
      ),
    'getNetworkKnowledgeEvents' : IDL.Func(
        [IDL.Text, IDL.Text],
        [EventsResult],
        ['query'],
      ),
    'getNetworkKnowledgeStats' : IDL.Func([IDL.Text], [StatsResult], ['query']),
    'getNode' : IDL.Func([IDL.Text], [IDL.Opt(NodeRecord)], ['query']),
    'getNodeRegistryStats' : IDL.Func([], [NodeRegistryStats], ['query']),
    'getRefCount' : IDL.Func([Hash], [IDL.Opt(IDL.Nat)], ['query']),
    'getStorageStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBytes' : IDL.Nat,
            'versionCount' : IDL.Nat,
            'recordCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getVersionHistory' : IDL.Func([KnowledgeId], [IDL.Vec(VersionInfo)], []),
    'heartbeat' : IDL.Func([HeartbeatInput], [NodeResult], []),
    'importData' : IDL.Func(
        [ImportFormat, IDL.Vec(IDL.Nat8), ImportOptions],
        [ImportResult__1],
        [],
      ),
    'importKnowledge' : IDL.Func([ImportPayload], [ImportResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAuditEvents' : IDL.Func([], [IDL.Vec(AuditEvent)], ['query']),
    'listDedupEntries' : IDL.Func([], [IDL.Vec(DedupEntry)], ['query']),
    'listKnowledge' : IDL.Func([], [IDL.Vec(KnowledgeRecord)], []),
    'listMyNodes' : IDL.Func([], [IDL.Vec(NodeRecord)], ['query']),
    'listNetworkKnowledgeByKey' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ViewsResult],
        ['query'],
      ),
    'listNodes' : IDL.Func([], [IDL.Vec(NodeRecord)], ['query']),
    'listVersions' : IDL.Func([], [IDL.Vec(Version)], ['query']),
    'publishCapabilities' : IDL.Func(
        [PublishCapabilitiesInput],
        [NodeResult],
        [],
      ),
    'registerNode' : IDL.Func([RegisterNodeInput], [NodeResult], []),
    'removePayload' : IDL.Func([Hash], [IDL.Bool], []),
    'reportNetworkLoadV1' : IDL.Func([Load], [Policy], []),
    'restoreVersion' : IDL.Func(
        [KnowledgeId, IDL.Nat],
        [IDL.Opt(KnowledgeRecord)],
        [],
      ),
    'restoreVersionById' : IDL.Func([IDL.Nat], [IDL.Opt(Hash)], ['query']),
    'retrieveKnowledge' : IDL.Func(
        [KnowledgeId],
        [IDL.Opt(KnowledgeRecord)],
        [],
      ),
    'revokeNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
    'revokeNode' : IDL.Func([IDL.Text], [NodeResult], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchKnowledge' : IDL.Func([SearchQuery], [SearchResponse], []),
    'searchVerifiedKnowledgeV1' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'version' : IDL.Nat,
              'payloadHash' : IDL.Text,
              'recordId' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'setNetworkVerifierV1' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
    'storageAddressMapping' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Address)],
        ['query'],
      ),
    'storageAvailability' : IDL.Func([], [Availability], []),
    'storageCapacity' : IDL.Func([], [Capacity], []),
    'storageIndex' : IDL.Func([], [IDL.Vec(Address)], []),
    'storageIntegrity' : IDL.Func([Address], [Integrity], []),
    'storageRead' : IDL.Func([Address], [Result_1], []),
    'storageWrite' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [Result], []),
    'storeKnowledge' : IDL.Func([KnowledgeInput], [KnowledgeId], []),
    'submitNetworkKnowledge' : IDL.Func(
        [SubmitNetworkKnowledgeInput],
        [ViewResult],
        [],
      ),
    'updateKnowledge' : IDL.Func(
        [KnowledgeInput],
        [IDL.Opt(KnowledgeRecord)],
        [],
      ),
    'verifyBatch' : IDL.Func(
        [IDL.Vec(Hash)],
        [IDL.Vec(VerificationResult)],
        ['query'],
      ),
    'verifyKnowledge' : IDL.Func([KnowledgeId], [VerifyResult], []),
    'verifyNetworkKnowledge' : IDL.Func([StatusActionInput], [ViewResult], []),
    'verifyPayload' : IDL.Func(
        [Hash, IDL.Vec(IDL.Nat8)],
        [VerificationState],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };